### ISSUE TITLE
Cuda runs of Memory with Max_sequence of 8

### ISSUE THREAD

**Issue by elnazsn1988** [microsoft/unilm#102]
Hi @ranpox , thanks for your code - I was running out of CUDA memory with the max seq defined as 512, so I tried 128, then 32, then 8, and am still getting running out of CUDA memory Errors. I have a GeForce RTX 2070, error is : 

```
aesnj@LAPTOP-T9IPSSI4 MINGW32 /c/projects/python-virtual-environments/unilm/layoutlm (master)
$ python run_seq_labeling.py  --data_dir data --model_type layoutlm  --model_name_or_path C:/projects/mcrs_dat/layoutlm-large-uncased-20200401T192902Z-001/layoutlm-large-uncased --do_lower_case --max_seq_length 8 --do_train --num_train_epochs 100.0 --logging_steps 10 --save_steps -1 --output_dir C:/projects/mcrs_dat/outp --labels data/labels.txt --per_gpu_train_batch_size 16 --fp16
2020-04-05 18:32:51.523077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-04-05 18:32:55.869679: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-05 18:32:57.006664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.29
pciBusID: 0000:01:00.0
2020-04-05 18:32:57.006977: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-04-05 18:32:57.007601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-05 18:32:57.008009: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-05 18:32:57.011795: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.29
pciBusID: 0000:01:00.0
2020-04-05 18:32:57.012151: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-04-05 18:32:57.012696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-05 18:32:57.566433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-05 18:32:57.566696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-04-05 18:32:57.566860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-04-05 18:32:57.567666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6306 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Epoch:   0%|          | 0/100 [00:00<?, ?it/s]
Iteration:   0%|          | 0/10 [00:00<?, ?it/s]C:\Users\aesnj\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\optim\lr_scheduler.py:91: UserWarning: Seems like `optimizer.step()` has been overridden after learning rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0

Iteration:  10%|#         | 1/10 [00:01<00:10,  1.14s/it]Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0

Iteration:  20%|##        | 2/10 [00:01<00:07,  1.08it/s]
Iteration:  30%|###       | 3/10 [00:02<00:05,  1.23it/s]Traceback (most recent call last):
  File "run_seq_labeling.py", line 856, in <module>
    main()
  File "run_seq_labeling.py", line 751, in main
    args, train_dataset, model, tokenizer, labels, pad_token_label_id
  File "run_seq_labeling.py", line 227, in train
    scaled_loss.backward()
  File "C:\Users\aesnj\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\aesnj\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\autograd\__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.12 GiB already allocated; 10.97 MiB free; 15.50 MiB cached)

```

**Comment by ankitkhadria1** [comment]
According to this issue, you can update pytorch version or reduce batch size and after reducing batch size its working for me.

https://github.com/pytorch/pytorch/issues/16417
