### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by acer22969** [microsoft/unilm#515]
**Describe the bug**
Model I am using (trocr-base-handwritten.pt):

**To Reproduce**
1. install success
2. run : python pic_inference.py

**Expected behavior**
/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
| [label] load dictionary: 50265 types
Downloading: "https://github.com/pytorch/fairseq/archive/main.zip" to /home/jimmy/.cache/torch/hub/main.zip
Traceback (most recent call last):
  File "pic_inference.py", line 70, in <module>
    model, cfg, task, generator, bpe, img_transform, device = init(model_path, beam)
  File "pic_inference.py", line 15, in init
    arg_overrides={"beam": beam, "task": "text_recognition", "data": "", "fp16": False})
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 387, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/fairseq/tasks/fairseq_task.py", line 633, in build_model
    model = models.build_model(args, self)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/jimmy/Desktop/trocr/unilm/trocr/deit_models.py", line 427, in build_model
    roberta = torch.hub.load('pytorch/fairseq:main', 'roberta.large')
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/torch/hub.py", line 396, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/torch/hub.py", line 71, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jimmy/.cache/torch/hub/pytorch_fairseq_main/hubconf.py", line 49, in <module>
    import fairseq.data.token_block_utils_fast  # noqa
  File "fairseq/data/token_block_utils_fast.pyx", line 1, in init fairseq.data.token_block_utils_fast
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

- Platform:ubuntu 14.04
- Python version:3.7
- PyTorch version (GPU?):3.7.11 (GPU:TAITAN)

**Comment by wangjiaqiys** [comment]
> 

It worked for me，thanks！

**Comment by wangjiaqiys** [comment]
> Although I had installed `numpy=1.21.2`, which is higher than the one the [StackOverflow question](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp/66138833#66138833) refers to, the advice to update numpy to `numpy=1.22.1` worked for me.
> 
> ```
> pip install --upgrade numpy
> ```
> 
> or
> 
> ```
> pip uninstall numpy
> pip install numpy
> ```

It worked for me， thanks!
